import { Meta, StoryObj } from '@storybook/react-vite';
import { Avatar } from '../../../components/avatar';
declare const meta: Meta<typeof Avatar>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const DefaultAvatarXXS: Story;
export declare const PictureAvatarXXS: Story;
export declare const DefaultAvatarXS: Story;
export declare const PictureAvatarXS: Story;
export declare const DefaultAvatarSM: Story;
export declare const PictureAvatarSM: Story;
export declare const DefaultAvatarBase: Story;
export declare const PictureAvatarBase: Story;
export declare const DefaultAvatarLG: Story;
export declare const PictureAvatarLG: Story;
export declare const DefaultAvatarXL: Story;
export declare const PictureAvatarXL: Story;
