name: Cypress Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build the project
        run: yarn build

      - name: Run Tests
        run: yarn test

      - name: Tests Artifactis
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vitest-report
          path: tests/videos/**/*
